import { Event, Speaker, Brand, TeamMember, Differentiator, NavItem } from '@/types';

// Navigation items
export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Events',
    href: '/events',
    children: [
      { label: '2025 Summit', href: '/events/2025-summit' },
      { label: '2024 Summit', href: '/events/2024-summit' },
      { label: '2023 Summit', href: '/events/2023-summit' },
      { label: 'Leadership Conference', href: '/events/leadership-conference' },
      { label: 'H.E.A.L. Forum', href: '/events/heal-forum' },
    ]
  },
  { label: 'Speakers', href: '/speakers' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

// Differentiator cards
export const differentiators: Differentiator[] = [
  {
    id: '1',
    title: 'Science Over Marketing',
    description: 'Most wellness events are pay-for-play. We focus on science-based speakers and brands with peer-reviewed research.',
    image: '/images/differentiators/science.svg',
  },
  {
    id: '2',
    title: 'Building Economic Value',
    description: 'Longevity is one of the best economic opportunities of our time. We help more people participate in this trillion-dollar market.',
    image: '/images/differentiators/investment.svg',
  },
  {
    id: '3',
    title: 'Community',
    description: 'We\'re building an ecosystem to extend healthspan for all humanity. Together we can overcome our epidemic of disease and suffering.',
    image: '/images/differentiators/community.svg',
  },
  {
    id: '4',
    title: 'Aligned With Nature',
    description: 'Most health events are in hotels and convention centers. We\'re embedded in the natural world—enjoy the sun, sea, and clean air.',
    image: '/images/differentiators/nature.svg',
  },
  {
    id: '5',
    title: 'Experiential',
    description: 'Transforming human health requires effort. We\'re here to inspire and transform through immersive, hands-on experiences.',
    image: '/images/differentiators/experiential.svg',
  },
  {
    id: '6',
    title: 'Innovation & Creativity',
    description: 'Our ecosystem is building for the future, not the past. Meet the brands and thought leaders at the peak of the next wave.',
    image: '/images/differentiators/innovation.svg',
  },
];

// Featured speakers
export const speakers: Speaker[] = [
  {
    id: '1',
    slug: 'dr-patrick-porter',
    name: 'Dr. Patrick Porter',
    role: 'Founder & CEO',
    organization: 'BrainTap',
    headshot: '/images/speakers/patrick-porter.svg',
    shortBio: 'Pioneer in brainwave entrainment technology and founder of BrainTap, helping millions optimize brain health.',
    fullBio: 'Dr. Patrick Porter is an award-winning author and speaker who has devoted his career to neuroscience and brainwave entrainment technology.',
    linkedIn: 'https://linkedin.com/in/drpatrickporter',
    isFeatured: true,
    expertise: ['Medical', 'Wellness'],
  },
  {
    id: '2',
    slug: 'bryan-johnson',
    name: 'Bryan Johnson',
    role: 'Founder',
    organization: 'Blueprint / Kernel',
    headshot: '/images/speakers/bryan-johnson.svg',
    shortBio: 'Tech entrepreneur and longevity pioneer, spending $2M annually to reverse his biological age.',
    fullBio: 'Bryan Johnson is a tech entrepreneur who sold Braintree Venmo to PayPal for $800M. He now dedicates his life to Project Blueprint, an effort to slow and reverse aging.',
    linkedIn: 'https://linkedin.com/in/bryanjohnson',
    website: 'https://blueprint.bryanjohnson.co',
    isFeatured: true,
    expertise: ['Research', 'Investment'],
  },
  {
    id: '3',
    slug: 'dr-joy-kong',
    name: 'Dr. Joy Kong',
    role: 'President',
    organization: 'American Academy of Integrative Cell Therapy',
    headshot: '/images/speakers/joy-kong.svg',
    shortBio: 'Board-certified physician specializing in regenerative medicine and stem cell therapy.',
    fullBio: 'Dr. Joy Kong is a UCLA-trained, triple board-certified physician and a leading expert in regenerative medicine.',
    isFeatured: true,
    expertise: ['Medical', 'Research'],
  },
  {
    id: '4',
    slug: 'aubrey-de-grey',
    name: 'Aubrey de Grey Ph.D',
    role: 'Chief Science Officer',
    organization: 'LEV Foundation',
    headshot: '/images/speakers/aubrey-de-grey.svg',
    shortBio: 'Biomedical gerontologist and author of "Ending Aging," pioneering the science of longevity escape velocity.',
    fullBio: 'Dr. Aubrey de Grey is a world-renowned biogerontologist and the leading voice in the anti-aging research field.',
    linkedIn: 'https://linkedin.com/in/aubreydegrey',
    isFeatured: true,
    expertise: ['Research', 'Medical'],
  },
  {
    id: '5',
    slug: 'rachele-brooke-smith',
    name: 'Rachele Brooke Smith',
    role: 'Actress & Wellness Advocate',
    organization: '',
    headshot: '/images/speakers/rachele-brooke-smith.svg',
    shortBio: 'Professional dancer, actress, and passionate advocate for holistic wellness and longevity.',
    isFeatured: true,
    expertise: ['Wellness', 'Fitness'],
  },
  {
    id: '6',
    slug: 'dr-william-seeds',
    name: 'Dr. William Seeds',
    role: 'Chairman',
    organization: 'Seeds Scientific Research & Performance Institute',
    headshot: '/images/speakers/william-seeds.svg',
    shortBio: 'Orthopedic surgeon and leading researcher in peptide therapy for regenerative medicine.',
    fullBio: 'Dr. William Seeds is a board-certified orthopedic surgeon and founder of the Seeds Scientific Research & Performance Institute.',
    isFeatured: true,
    expertise: ['Medical', 'Research'],
  },
  {
    id: '7',
    slug: 'dr-mindy-pelz',
    name: 'Dr. Mindy Pelz',
    role: 'Bestselling Author',
    organization: 'The Resetter Podcast',
    headshot: '/images/speakers/mindy-pelz.svg',
    shortBio: 'Nutrition and functional health expert, bestselling author of "Fast Like a Girl."',
    fullBio: 'Dr. Mindy Pelz is a bestselling author, keynote speaker, and nutrition and functional health expert who has spent over two decades helping thousands of people successfully reclaim their health.',
    linkedIn: 'https://linkedin.com/in/drmindypelz',
    website: 'https://drmindypelz.com',
    isFeatured: true,
    expertise: ['Wellness', 'Medical'],
  },
  {
    id: '8',
    slug: 'dr-olivia-lesslar',
    name: 'Dr. Olivia Lesslar',
    role: 'Medical Director',
    organization: 'Next Health',
    headshot: '/images/speakers/olivia-lesslar.svg',
    shortBio: 'Integrative medicine specialist focused on preventive health optimization and longevity protocols.',
    isFeatured: false,
    expertise: ['Medical', 'Wellness'],
  },
  {
    id: '9',
    slug: 'stephen-mccain',
    name: 'Stephen McCain',
    role: 'CEO',
    organization: 'Conscious Health Center',
    headshot: '/images/speakers/stephen-mccain.svg',
    shortBio: 'Healthcare entrepreneur dedicated to making regenerative medicine accessible to all.',
    isFeatured: false,
    expertise: ['Investment', 'Wellness'],
  },
  {
    id: '10',
    slug: 'susan-bratton',
    name: 'Susan Bratton',
    role: 'CEO',
    organization: 'Personal Life Media',
    headshot: '/images/speakers/susan-bratton.svg',
    shortBio: 'Intimacy wellness expert and trusted advisor on sexual vitality and longevity.',
    isFeatured: false,
    expertise: ['Wellness'],
  },
];

// Brand partners
export const brands: Brand[] = [
  { id: '1', name: 'Fatty15', logo: '/images/brands/fatty15.svg', url: 'https://fatty15.com/', isActive: true },
  { id: '2', name: 'Routine Skin', logo: '/images/brands/routine-skin.svg', url: 'https://www.routineskin.com/', isActive: true },
  { id: '3', name: 'Pulse PEMF', logo: '/images/brands/pulse-pemf.svg', url: 'https://pulsepemf.com/', isActive: true },
  { id: '4', name: 'Niagen Plus', logo: '/images/brands/niagen-plus.svg', url: 'https://www.niagenplus.com/', isActive: true },
  { id: '5', name: 'The Good For Co', logo: '/images/brands/good-for-co.svg', url: 'https://thegoodforco.com/', isActive: true },
  { id: '6', name: 'Silver Biotics', logo: '/images/brands/silver-biotics.svg', url: 'https://silverbiotics.com/', isActive: true },
  { id: '7', name: 'SSRP Institute', logo: '/images/brands/ssrp.svg', url: 'https://ssrpinstitute.org/', isActive: true },
  { id: '8', name: 'Your Soma', logo: '/images/brands/your-soma.svg', url: 'https://www.yoursoma.com/', isActive: true },
  { id: '9', name: 'Snip Nutrition', logo: '/images/brands/snip-nutrition.svg', url: 'https://www.snipnutrition.com/', isActive: true },
];

// Events data
export const events: Event[] = [
  {
    id: '0',
    slug: '2025-summit',
    title: '2025 Healthspan Summit',
    date: '2025-10-14',
    endDate: '2025-10-16',
    location: 'Malibu, California',
    venue: 'Calamigos Guest Ranch',
    status: 'upcoming',
    description: 'Join us for the third annual Healthspan Summit—three transformative days of cutting-edge longevity science, immersive wellness experiences, and unparalleled networking with the world\'s leading researchers, physicians, and innovators.',
    shortDescription: 'Three days of transformative longevity science and experiential wellness in beautiful Malibu.',
    heroImage: '/images/events/conference-2025.jpg',
    ticketUrl: 'https://forms.gle/3xKPNwWEaPssmDKJA',
    speakerIds: ['1', '2', '3', '4', '6', '7'],
    eventType: 'summit',
  },
  {
    id: '1',
    slug: '2024-summit',
    title: '2024 Healthspan Summit',
    date: '2024-10-15',
    endDate: '2024-10-17',
    location: 'Malibu, California',
    venue: 'Calamigos Guest Ranch',
    status: 'past',
    description: 'Our flagship summit bringing together the world\'s leading longevity researchers, physicians, and innovators for three days of cutting-edge science, networking, and experiential wellness.',
    shortDescription: 'Three days of cutting-edge longevity science and experiential wellness in beautiful Malibu.',
    heroImage: '/images/events/2024-summit-hero.svg',
    heroVideo: '/videos/2024-summit.mp4',
    gallery: [
      '/images/events/2024-summit/gallery-1.svg',
      '/images/events/2024-summit/gallery-2.svg',
      '/images/events/2024-summit/gallery-3.svg',
    ],
    speakerIds: ['1', '2', '3', '4', '5', '6', '7', '8'],
    eventType: 'summit',
  },
  {
    id: '2',
    slug: '2023-summit',
    title: '2023 Healthspan Summit',
    date: '2023-10-10',
    endDate: '2023-10-12',
    location: 'Malibu, California',
    venue: 'Calamigos Guest Ranch',
    status: 'past',
    description: 'The inaugural Healthspan Summit, establishing our vision of bringing together the brightest minds in longevity science.',
    shortDescription: 'The inaugural summit that started the Healthspan movement.',
    heroImage: '/images/events/2023-summit-hero.svg',
    gallery: [],
    speakerIds: ['1', '3', '5', '6', '9', '10'],
    eventType: 'summit',
  },
  {
    id: '3',
    slug: 'leadership-conference',
    title: 'Longevity Leadership Conference 2025',
    date: '2025-01-20',
    endDate: '2025-01-21',
    location: 'Los Angeles, California',
    status: 'past',
    description: 'An exclusive gathering for longevity industry leaders, investors, and executives to shape the future of healthspan.',
    shortDescription: 'Exclusive gathering for longevity industry leaders and investors.',
    heroImage: '/images/events/leadership-conference-hero.svg',
    speakerIds: ['2', '4', '8', '9'],
    eventType: 'conference',
  },
  {
    id: '4',
    slug: 'heal-forum',
    title: 'H.E.A.L. Forum',
    date: '2023-01-15',
    location: 'Los Angeles, California',
    status: 'past',
    description: 'Health, Education, Action, and Longevity—our founding event that launched Healthspan Productions.',
    shortDescription: 'Our founding event that launched Healthspan Productions.',
    heroImage: '/images/events/heal-forum-hero.svg',
    speakerIds: ['1', '6', '10'],
    eventType: 'forum',
  },
];

// Team members
export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Elias Arjan',
    role: 'Founder & CEO',
    image: '/images/team/elias-arjan.svg',
    bio: 'Elias Arjan is the visionary founder of Healthspan Productions, dedicated to bringing evidence-based longevity science to the masses through world-class events and media.',
    linkedIn: 'https://linkedin.com/in/eliasarjan',
  },
  {
    id: '2',
    name: 'Adam Torres',
    role: 'Co-Host & Strategic Partner',
    image: '/images/team/adam-torres.svg',
    bio: 'Adam Torres is CEO of Mission Matters Media, bringing over a decade of media experience to Healthspan Productions.',
    linkedIn: 'https://linkedin.com/in/adamtorres',
  },
  {
    id: '3',
    name: 'Chirag Sagar',
    role: 'Co-Host',
    image: '/images/team/chirag-sagar.svg',
    bio: 'Chirag Sagar is a healthcare entrepreneur and advocate for integrative medicine approaches to longevity.',
  },
];

// Social links
export const socialLinks = {
  linkedIn: 'https://www.linkedin.com/company/healthspanpro/',
  instagram: 'https://www.instagram.com/healthspanevents/',
  youtube: 'https://www.youtube.com/@healthspanproductions',
};

// External links
export const externalLinks = {
  collective: 'https://nas.io/healthspan-collective',
  eventApplication: 'https://forms.gle/3xKPNwWEaPssmDKJA',
  luma: 'https://luma.com/healthspan',
};

// Company info
export const companyInfo = {
  name: 'Healthspan Productions',
  tagline: 'Extend Your Healthspan',
  vision: 'Our vision is a society where living to 100 in excellent health is the norm, not the exception. We see a future where every generation benefits from scientific advancements in health and longevity.',
  mission: 'Healthspan Productions collaborates with global leaders to produce groundbreaking media and events that advance the science and practice of longevity.',
  email: 'connect@healthspanevents.com',
  founded: 'January 2023',
  location: 'Los Angeles, California',
};
